name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Aquí se añaden los assets, incluyendo la ruta de la imagen
  assets:
    - assets/Images/Malaga.jpg
    - assets/Images/Cadiz.jpeg
    - assets/Images/Granada.webp
    - assets/Images/perfil.jpg
    - assets/Images/Cordoba.webp
    - assets/Images/Sevilla.webp
    - assets/Images/Almeria.jpg
    - assets/Images/Huelva.jpg
    - assets/Images/Estepona.jpg
    - assets/Images/Jaen.jpeg
    - assets/Images/telefono.jpg
    - assets/Images/whatsapp.png
    - assets/Images/instagram.webp
    - assets/Images/mensaje.webp
