name: flutter_healthylife
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_core: ^3.10.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  http: ^1.3.0
  url_launcher: ^6.1.14
  url_launcher_web: ^2.0.11
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Aquí se añaden los assets, incluyendo la ruta de la imagen
