name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.1
  provider: ^6.1.2
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  shared_preferences: ^2.5.3
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/ListaYaLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Images/ListaYaLogo.png
    - assets/Images/Google.png
